/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as HistoriasIdRouteImport } from './routes/historias.$id'
import { Route as ProyectosIndexRouteImport } from './routes/proyectos.index'
import { Route as ProyectosIdRouteImport } from './routes/proyectos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriasIdRoute = HistoriasIdRouteImport.update({
  id: '/historias/$id',
  path: '/historias/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIndexRoute = ProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosIdRoute = ProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/equipo': typeof EquipoRoute
  '/historias/$id': typeof HistoriasIdRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/equipo': typeof EquipoRoute
  '/historias/$id': typeof HistoriasIdRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/proyectos': typeof ProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/equipo': typeof EquipoRoute
  '/historias/$id': typeof HistoriasIdRoute
  '/proyectos/$id': typeof ProyectosIdRoute
  '/proyectos/': typeof ProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/equipo' | '/historias/$id' | '/proyectos/$id' | '/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/equipo' | '/historias/$id' | '/proyectos/$id' | '/proyectos'
  id:
    | '__root__'
    | '/'
    | '/equipo'
    | '/historias/$id'
    | '/proyectos/$id'
    | '/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EquipoRoute: typeof EquipoRoute
  HistoriasIdRoute: typeof HistoriasIdRoute
  ProyectosIdRoute: typeof ProyectosIdRoute
  ProyectosIndexRoute: typeof ProyectosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historias/$id': {
      id: '/historias/$id'
      path: '/historias/$id'
      fullPath: '/historias/$id'
      preLoaderRoute: typeof HistoriasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/': {
      id: '/proyectos/'
      path: '/proyectos'
      fullPath: '/proyectos/'
      preLoaderRoute: typeof ProyectosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos/$id': {
      id: '/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/proyectos/$id'
      preLoaderRoute: typeof ProyectosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EquipoRoute: EquipoRoute,
  HistoriasIdRoute: HistoriasIdRoute,
  ProyectosIdRoute: ProyectosIdRoute,
  ProyectosIndexRoute: ProyectosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
